# Generated by Django 3.1.4 on 2020-12-23 14:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201223_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='.', max_length=255),
            preserve_default=False,
        ),
    ]
